name: Pipeline

on:
  push:
    branches:
      - master
  pull_request:
    branches: [master]
    types: [opened, synchronize]

jobs:
  simple_deployment_pipeline:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - name: npm install 
        run: npm install  
      - name: lint
        run: npm run eslint
      - name: build
        run: npm run build
      - name: test
        run: npm run test
      - name: e2e tests
        uses: cypress-io/github-action@v2
        with:
          command: npm run test:e2e
          start: npm run start-prod
          wait-on: http://localhost:5000
      - name: deploy to heroku
        uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "pokedex-test-open" 
          heroku_email: "raheel.amjad.02@gmail.com"
          healthcheck: "https://pokedex-test-open.herokuapp.com/health"
          checkstring: "ok"
          rollbackonhealthcheckfailed: true
        if: ${{ !(contains(join(github.event.commits.*.message), '#skip')) && github.event_name == 'push' }}
      - name: Test Info
        uses: rjstone/discord-webhook-notify@v1
        with:
          severity: info
          details: New version of pokedex open deployed!.
          webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}
      - name: Test Warn
        uses: rjstone/discord-webhook-notify@v1
        with:
          severity: warn
          details: build has broken.
          webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}
  tag_release:
    needs: [simple_deployment_pipeline]
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: '0'
      - name: Bump version and push tag
        uses: anothrNick/github-tag-action@1.36.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEFAULT_BUMP: patch
        if: ${{ !(contains(join(github.event.commits.*.message), '#skip')) && github.event_name == 'push' }}
  